name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: version
    attributes:
      label: Python Version
      description: What version of Python are you running? (e.g. 3.9.1)
      placeholder: 3.9.1
    validations:
      required: true
  - type: input
    id: updownserver-version
    attributes:
      label: updownserver Version
      description: What version of updownserver are you running? (run `python -m updownserver --version` or check pip list)
      placeholder: 1.0.2
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you running on?
      options:
        - Windows 11
        - Windows 10
        - macOS
        - Linux
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How do we reproduce the bug?
      placeholder: |
        1. Run command '...'
        2. Make request to '....'
        3. See error
    validations:
      required: true
